"""Phase A-L: write one input file per execution unit — every live register block whose State names the unit, in full."""
import pathlib
import re
import sys

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))
import pass2_index  # noqa: E402

ROOT = pathlib.Path(__file__).resolve().parents[1]
C_RE = r"\bin C\b|hardware in C|\bC —|phase C"


def blocks():
    out = []
    for name in pass2_index.FILES:
        p = ROOT / "pass2" / f"{name}.md"
        for m in re.finditer(r"(?ms)^### ((?:G\d+|LEAD|REF)/R\d+) (.*?)\n(.*?)(?=^### |^## |\Z)", p.read_text()):
            f = dict(re.findall(r"(?m)^- \*\*(\w[\w ]*)\*\*: (.*)$", m.group(3)))
            if "merged into" in f.get("Lead", ""):
                continue
            out.append((m.group(1), f"### {m.group(1)} {m.group(2)}\n{m.group(3).rstrip()}", f.get("State", ""), name))
    return out


def main():
    out_dir = pathlib.Path(sys.argv[1])
    out_dir.mkdir(parents=True, exist_ok=True)
    all_blocks = blocks()
    for unit in sys.argv[2:]:
        if unit == "C":
            sel = [b for b in all_blocks if re.search(C_RE, b[2])]
        else:
            n = int(unit[1:])
            sel = [b for b in all_blocks if re.search(rf"\b{unit}\b", b[2])
                   or any(int(a) <= n <= int(z) for a, z in re.findall(r"\bU(\d+) ?[-–] ?U?(\d+)\b", b[2]))]
        text = [f"# A-L input — {unit} ({len(sel)} register blocks; generated by `audit/sweeps/al_input.py`)", ""]
        text += [f"<!-- from audit/pass2/{b[3]}.md -->\n{b[1]}\n" for b in sel]
        (out_dir / f"input_{unit}.md").write_text("\n".join(text))
        print(unit, len(sel))


if __name__ == "__main__":
    main()
