"""Allover pass 2: assign every pass-1 requirement (HR cluster or singleton) and routing line to one group."""
import collections
import pathlib
import re

ROOT = pathlib.Path(__file__).resolve().parents[1]
AREAS = {"G1": "HW", "G2": "TEST", "G3": "SENS ALGO BUS LED", "G4": "PLAT MEM PERF", "G5": "CORE STOR XCUT SEC",
         "G6": "UART NET REST", "G7": "TWIN WEB", "G8": "GEN TOOL SCR CI", "G9": "DOC PAR LIC", "G10": "ENV"}
PRIORITY = ["G5", "G4", "G3", "G6", "G8", "G7", "G2", "G1", "G9", "G10"]  # tie-break: domain owner first
CAND = re.compile(r"\bG(10|[1-9])\.(\d{3})\b")


def main():
    merge = (ROOT / "hreq" / "MERGE.md").read_text()
    clusters = {}
    for m in re.finditer(r"^### (HR\d{3}) (.+?)\n.*?^- \*\*Members\*\*: (.+?)$", merge, re.M | re.S):
        clusters[m.group(1)] = (m.group(2), [f"G{g}.{n}" for g, n in CAND.findall(m.group(3))])
    single = merge.split("Singletons: 369", 1)[1].split("###", 1)[0]
    singles = [f"G{g}.{n}" for g, n in CAND.findall(single)]
    owner = collections.defaultdict(list)
    for hr, (title, mem) in clusters.items():
        groups = [c.split(".")[0] for c in mem]
        cnt = collections.Counter(groups)
        best = max(cnt.values())
        grp = min((g for g in groups if cnt[g] == best), key=PRIORITY.index)
        owner[grp].append(f"{hr} ({', '.join(mem)}) {title}")
    for c in singles:
        owner[c.split(".")[0]].append(c)
    out = ["# Allover pass 2 — assignment (generated by `audit/sweeps/pass2_assign.py`)", "",
           f"{len(clusters)} clusters (owner group = plurality of members; tie: the code-domain group first, order G5 G4 G3 G6 G8 G7 G2 G1 G9 G10), {len(singles)} singletons.", ""]
    for g in AREAS:
        items = owner[g]
        out += [f"## {g} — plan areas: {AREAS[g]} — {len(items)} requirements", ""] + [f"- {i}" for i in items] + [""]
    (ROOT / "pass2" / "ASSIGN.md").write_text("\n".join(out))
    print({g: len(owner[g]) for g in AREAS}, sum(len(v) for v in owner.values()))


if __name__ == "__main__":
    main()
