"""Allover pass 2: generate audit/pass2/INDEX.md — requirements by OR row, execution unit and pillar, with counts."""
import collections
import pathlib
import re

ROOT = pathlib.Path(__file__).resolve().parents[1]
OVERTAKEN = {62: "OR62.a is overtaken by OR64.a"}
FILES = [f"G{n}" for n in range(1, 11)] + ["LEAD"]


def requirements():
    out = []
    for name in FILES:
        p = ROOT / "pass2" / f"{name}.md"
        if not p.exists():
            continue
        for m in re.finditer(r"(?ms)^### ((?:G\d+|LEAD)/R\d+) (.*?)\n(.*?)(?=^### |^## |\Z)", p.read_text()):
            f = dict(re.findall(r"(?m)^- \*\*(\w[\w ]*)\*\*: (.*)$", m.group(3)))
            out.append((m.group(1), m.group(2), f))
    return out


def main():
    reqs = requirements()
    live = [r for r in reqs if "Lead" not in r[2] or "merged into" not in r[2]["Lead"]]
    by_or, by_unit, by_pillar = collections.defaultdict(list), collections.defaultdict(list), collections.defaultdict(list)
    rank, kind, holds = collections.Counter(), collections.Counter(), 0
    for rid, _title, f in live:
        for n in sorted({int(x) for x in re.findall(r"\bOR(\d+)", f.get("Sources", "") + " " + f.get("Rank", ""))}):
            by_or[n].append(rid)
        state = f.get("State", "")
        units = sorted(set(re.findall(r"\bU(\d+)\b", state)), key=int)
        for u in units:
            by_unit[f"U{u}"].append(rid)
        if re.search(r"\bin C\b|hardware in C|\bC —|phase C", state):
            by_unit["C"].append(rid)
        if state.lower().startswith("holds"):
            holds += 1
        for k in ("code", "doc", "test", "rule", "hardware"):
            if re.search(rf"\b{k}\b", state):
                kind[k] += 1
        rank[(f.get("Rank", "").split(" ")[0].strip("—").lower() or "?")] += 1
        for pl in re.findall(r"\bP\d+\b|process", f.get("Pillar", "")) or ["?"]:
            by_pillar[pl].append(rid)
    lines = ["# Allover pass 2 — index (generated by `audit/sweeps/pass2_index.py`; do not edit)", "",
             f"Requirements: {len(reqs)} written, {len(reqs) - len(live)} merged into another, **{len(live)} live**. "
             f"State: {holds} hold at HEAD, {len(live) - holds} carry work. Work kinds (a requirement may carry several): "
             + ", ".join(f"{k} {v}" for k, v in kind.most_common()) + ".",
             "Rank: " + ", ".join(f"{k} {v}" for k, v in rank.most_common()) + ".", "",
             "## By pillar", ""]
    lines += [f"- **{p}** ({len(v)}): " + ", ".join(v) for p, v in sorted(by_pillar.items(), key=lambda kv: (kv[0] == "process", int(kv[0][1:]) if kv[0][1:].isdigit() else 99))]
    lines += ["", "## By execution unit (plan 4.1; C = phase C hardware rounds)", ""]
    lines += [f"- **{u}** ({len(v)}): " + ", ".join(v) for u, v in sorted(by_unit.items(), key=lambda kv: (kv[0] == "C", int(kv[0][1:]) if kv[0][1:].isdigit() else 99))]
    lines += ["", "## By owner row (every OR1-OR78 carried by at least one requirement)", ""]
    lines += [f"- **OR{n}** ({len(by_or[n])}): " + ", ".join(by_or[n]) for n in range(1, 81)]
    missing = [n for n in range(1, 81) if not by_or[n] and n not in OVERTAKEN]
    lines += ["", f"OR rows without a live requirement: {', '.join(f'OR{n}' for n in missing) or 'none'} (" + "; ".join(OVERTAKEN.values()) + ").", ""]
    (ROOT / "pass2" / "INDEX.md").write_text("\n".join(lines))
    print(len(reqs), len(live), holds, dict(kind), dict(rank), "missing OR", missing)


if __name__ == "__main__":
    main()
