"""Collect every NEW/KNOWN+ line of the refined-harvest sweeps into audit/refined/FINDINGS.md, one stable
RF id each, grouped by the register file its home names (NEW when it names none)."""
import collections
import glob
import re

rows = []
for f in sorted(glob.glob("audit/refined/S[0-9][0-9].md")):
    sweep = f[-6:-3]
    for line in open(f):
        m = re.match(r"\s*-\s*(RP\d+)[.\w()]*\s*\|\s*(NEW|KNOWN\+)\s*\|", line)
        if not m:
            continue
        home = re.search(r"home:\s*([^|]*)", line)
        h = home.group(1) if home else ""
        reg = re.search(r"\b(G\d+|LEAD)/R\d+", h)
        group = reg.group(1) if reg else "NEW"
        om = bool(re.search(r"owner-matter:\s*y", line))
        rows.append((group, sweep, line.strip().lstrip("- ").strip(), om))

by = collections.defaultdict(list)
for i, (g, s, text, om) in enumerate(rows, 1):
    by[g].append((f"RF{i:03d}", s, text, om))
order = sorted(by, key=lambda g: (g == "NEW", g == "LEAD", int(g[1:]) if g[1:].isdigit() else 0))
out = ["# Refined harvest — findings (generated by `audit/sweeps/refined_merge.py`; do not edit)", "",
       f"{len(rows)} lines (NEW and KNOWN+) from sweeps S01-S13, grouped by the register file their home names; "
       f"{sum(r[3] for r in rows)} are owner-matter (⚑). Integration status lives in the register, not here.", ""]
for g in order:
    out += [f"## {g} ({len(by[g])})", ""]
    out += [f"- **{rid}** [{s}]{' ⚑' if om else ''} {t}" for rid, s, t, om in by[g]]
    out.append("")
open("audit/refined/FINDINGS.md", "w").write("\n".join(out))
print({g: len(by[g]) for g in order})
