#!/usr/bin/env bash
# Stages the real website (html/ + js/) for exactly one device into the shape
# scripts/build_frozen_html.sh expects, then invokes it. That script stays generic - this one's only
# job is building the single merged directory HTML_SRC_DIRS points at.
#
# SPECIFICATION.md Part H.2 owns what gets staged and why: the app.js rename, the never-staged
# mock-server.js, the import-stripping and concatenation-order rules. Part H.7 owns why bundling and
# inlining exist at all, and why keep-alive is deliberately not the answer.
#
# Usage: scripts/build_website.sh <device> [output_path]
#   <device>     matches an html/definitions/<device>.json file, e.g. "wozi".
#   output_path  forwarded to build_frozen_html.sh (default: frozen_modules/frozen_html.py).
set -euo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")/.."

device="${1:?Usage: scripts/build_website.sh <device> [output_path]}"
out_file="${2:-frozen_modules/frozen_html.py}"

stage_dir="$(mktemp -d)"
# Separate from stage_dir on purpose: stage_dir is the served /html content root and gets scanned
# whole, so a generated definitions.json written there would be frozen as an extra
# /definitions.json.gz and defeat H.7's inlining. scratch_dir never reaches the served tree.
scratch_dir="$(mktemp -d)"
trap 'rm -rf "$stage_dir" "$scratch_dir"' EXIT

# wozi/dev keep their hand-written html/definitions/<device>.json, which tests_js/'s PUT-matrix
# fixtures load straight off disk; retiring them is deferred work (SPECIFICATION.md Part L.4).
# Every other device has none, so buildgen generates one here rather than failing the build.
definitions_src="html/definitions/${device}.json"
if [[ ! -f "$definitions_src" ]]; then
    device_toml="devices/${device}.toml"
    if [[ ! -f "$device_toml" ]]; then
        echo "error: no definitions file at $definitions_src and no $device_toml to generate one from" >&2
        exit 1
    fi
    definitions_src="$scratch_dir/definitions.json"
    python3 -m buildgen.definitions "$device_toml" --src-dir src --out "$definitions_src"
fi

STAGE_DIR="$stage_dir" DEFINITIONS_SRC="$definitions_src" python3 <<'PYEOF'
import os

stage_dir = os.environ["STAGE_DIR"]
definitions_src = os.environ["DEFINITIONS_SRC"]

with open("html/index.html", encoding="utf-8") as f:
    html = f.read()
with open("html/style.css", encoding="utf-8") as f:
    css = f.read()
with open(definitions_src, encoding="utf-8") as f:
    definitions_json = f.read()

# chr(92) rather than a literal backslash, to keep this heredoc's own escaping unambiguous. The
# result is JSON's own escape for "<", identical to a literal "<" once parsed; escaping every one of
# them is what stops a field value containing "</script" from closing the tag early (Part H.7).
escaped_lt = chr(92) + "u003c"
definitions_json = definitions_json.replace("<", escaped_lt)

link_tag = '<link rel="stylesheet" href="style.css">'
if link_tag not in html:
    raise SystemExit("html/index.html's stylesheet <link> tag not found - update build_website.sh")
html = html.replace(link_tag, "<style>\n" + css + "</style>")

inlined_script = '<script type="application/json" id="inlined-definitions">' + definitions_json + "</script>\n"
if "</head>" not in html:
    raise SystemExit("html/index.html has no </head> - update build_website.sh")
html = html.replace("</head>", inlined_script + "</head>")

with open(os.path.join(stage_dir, "index.html"), "w", encoding="utf-8") as f:
    f.write(html)
PYEOF

mkdir -p "$stage_dir"/js
{
    echo "// Generated by scripts/build_website.sh - concatenation of js/field-format.js, poll-manager.js,"
    echo "// templates.js, definitions.js, render.js, nav.js, main.js (in that dependency order). Do not"
    echo "// edit directly - edit the source files under js/ instead. See this script's own header comment for why."
    for src in js/field-format.js js/poll-manager.js js/templates.js js/definitions.js js/render.js js/nav.js js/main.js; do
        echo ""
        echo "// ---- $src ----"
        grep -v -E '^import .* from "\./[^"]+\.js";$' "$src"
    done
} > "$stage_dir"/js/app.js

HTML_SRC_DIRS="$stage_dir" scripts/build_frozen_html.sh "$out_file"
