#!/usr/bin/env bash
# Stages the real website (html/ + js/) for exactly one device into the shape scripts/
# build_frozen_html.sh expects, then invokes it. See WEBSITE_PLAN.md §10 item 4 for the design
# this follows and the gaps it closes; scripts/build_frozen_html.sh itself is unchanged by this
# script's existence - it stays a generic "merge N source dirs, gzip, freezefs" pipeline, this
# script's own job is only building the one merged dir HTML_SRC_DIRS points at.
#
# What gets staged, and why each rename/selection exists:
#   - html/index.html, html/style.css - copied verbatim.
#   - html/definitions/<device>.json -> definitions.json (renamed, no "definitions/" nesting) -
#     a real device's firmware only ever ships its own one definitions file, so js/main.js fetches
#     a fixed "definitions.json" rather than needing a "device" constant baked into checked-in JS
#     (mirrors how html/index.html itself never branches on device - WEBSITE_PLAN.md §4's
#     "per-device page-scheme mechanism" row).
#   - The production JS module set (js/poll-manager.js, templates.js, definitions.js, render.js,
#     nav.js, main.js) - concatenated into one bundled js/app.js (see "Bundling" below), not copied
#     as separate files. js/mock-server.js (prototype-only fake backend) is deliberately NOT
#     staged at all - its fetch-patching has no business anywhere near production.
#   - The bundle is staged as js/app.js on purpose: html/index.html's own `<script>` imports
#     "../js/app.js" unconditionally, and that one path is meant to stay identical between
#     `npm run preview` (serves the real repo layout, where js/app.js is the separate,
#     prototype-only entry file) and a real device build (where the staged js/app.js is really the
#     bundle below) - see WEBSITE_PLAN.md §10 item 4's "no production entry point exists yet" note.
#     Staging under this name means html/index.html never needs a build-time text rewrite.
#
# Bundling (WEBSITE_PLAN.md §10 item 5): concatenated into one file, not copied as 6 separate
# js/*.js files, so a single page load opens far fewer concurrent TCP connections - the real
# rp2040 lwIP build's MEMP_NUM_TCP_PCB=5 (lwIP's own default, confirmed against the vendored
# source, no project override) is a hard ceiling on simultaneously active TCP connections that no
# amount of src/asy_webserver_service.py tuning can raise; 6 separate JS files plus index.html plus
# style.css could alone exceed it on a single browser tab's first paint, before any other client
# (e.g. an OpenHAB instance polling REST endpoints) even connects. Concatenation order matters -
# each file only ever appears after every local file it imports from, so a `const`/class needed by
# a later file already exists by the time that file's top-level code runs (function declarations
# are hoisted regardless, so strict ordering only matters for the few top-level `const`s -
# poll-manager.js's DEFAULT_TIMEOUT_MS/pollManager, definitions.js's SUPPORTED_SCHEMA_MAJOR - but
# kept consistent throughout rather than relying on that distinction). Every file's own
# `import { ... } from "./local-file.js";` line is dropped (`grep -v`) since after concatenation
# every imported name is already in scope from earlier in the same file; each file's own `export`
# keywords are left as-is - a module script can freely contain unused exports, and stripping them
# would be one more thing that could get the regex wrong for no real benefit. This is a plain,
# dependency-free text concatenation (matching this project's own small/lean/no-build-step-magic
# philosophy - WEBSITE_PLAN.md §3), not a real bundler - safe here specifically because every
# production js/*.js file uses only simple `import { name, ... } from "./relative.js"` (no default
# exports, no dynamic imports, no re-exports, no naming collisions across files - confirmed by
# direct inspection, and cross-checked mechanically below) rather than because concatenation is a
# generally-safe substitute for real bundling.
#
# Usage: scripts/build_website.sh <device> [output_path]
#   <device>     matches an html/definitions/<device>.json file, e.g. "wozi".
#   output_path  forwarded to build_frozen_html.sh (default: frozen_modules/frozen_html.py).
set -euo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")/.."

device="${1:?Usage: scripts/build_website.sh <device> [output_path]}"
out_file="${2:-frozen_modules/frozen_html.py}"

definitions_src="html/definitions/${device}.json"
if [[ ! -f "$definitions_src" ]]; then
    echo "error: no definitions file at $definitions_src" >&2
    exit 1
fi

stage_dir="$(mktemp -d)"
trap 'rm -rf "$stage_dir"' EXIT

cp html/index.html html/style.css "$stage_dir"/
cp "$definitions_src" "$stage_dir"/definitions.json

mkdir -p "$stage_dir"/js
{
    echo "// Generated by scripts/build_website.sh - concatenation of js/poll-manager.js, templates.js,"
    echo "// definitions.js, render.js, nav.js, main.js (in that dependency order). Do not edit directly -"
    echo "// edit the source files under js/ instead. See this script's own header comment for why."
    for src in js/poll-manager.js js/templates.js js/definitions.js js/render.js js/nav.js js/main.js; do
        echo ""
        echo "// ---- $src ----"
        grep -v -E '^import .* from "\./[^"]+\.js";$' "$src"
    done
} > "$stage_dir"/js/app.js

HTML_SRC_DIRS="$stage_dir" scripts/build_frozen_html.sh "$out_file"
