#!/usr/bin/env bash
# Builds the website placeholder's frozen static-content module (SPECIFICATION.md Part A.9):
# gzip each file in html_stub/ -> ext/freezefs (vendored, unmodified, "python -m freezefs", current
# CLI - see ext/freezefs/archive.py) packs the pre-gzipped files into a self-mounting frozen Python
# module. Mirrors build-wozi.sh's own pipeline shape (cp -> gzip -9 -> freezefs -> assemble), not its
# literal freezefs invocation, which predates freezefs 2.4's current CLI (no more "-s" flag).
#
# Deliberately no --compress: that flag switches freezefs to on-device deflate decompression, which
# is incompatible with this project's existing approach (pre-gzip by hand, serve via Microdot's
# send_file(compressed=True, file_extension='.gz'), which only ever sets the Content-Encoding header
# and never decompresses on-device) - see SPECIFICATION.md Part A.9.
#
# Output is a plain build artifact, never committed (matches build-wozi.sh's own html/build/
# handling) - regenerated by scripts/test.sh before running tests, and by the real firmware build
# once that's genericized (BACKLOG.md's "Dev/build environment setup").
#
# Usage: scripts/build_frozen_html.sh [output_path]
#   output_path defaults to frozen_modules/frozen_html.py - deliberately NOT .frozen/: that exact
#   string is a hardcoded sentinel in MicroPython's own import machinery (py/builtinimport.c's
#   MP_FROZEN_PATH_PREFIX ".frozen/") that routes straight to the compiled-in frozen-module table
#   and never touches the real filesystem - confirmed directly against the pinned v1.28.0 source
#   after a real file placed there turned out to be silently unimportable (`ImportError: no module
#   named 'frozen_html'` even though the file was really on disk). scripts/test.sh adds
#   frozen_modules/ as its own MICROPYPATH segment, separate from (and alongside) the real ".frozen"
#   sentinel it already needs for `import asyncio` etc.
#
# Source directory(ies) default to html_stub - override via the HTML_SRC_DIRS env var, a
# space-separated list of directories whose contents are merged into one flat build tree before
# gzipping. This is what lets this same script build the real website later without editing it:
# build-wozi.sh's own legacy pipeline merged html_raw/general (shared) with a board-specific folder
# (html_raw/wozi, /dev, /arzi) the same way - e.g. once the real content lands,
# `HTML_SRC_DIRS="html/general html/wozi" scripts/build_frozen_html.sh` reuses this script as-is.
set -euo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")/.."

src_dirs="${HTML_SRC_DIRS:-html_stub}"
out_file="${1:-frozen_modules/frozen_html.py}"
mount_target="/html"

tmp_dir="$(mktemp -d)"
trap 'rm -rf "$tmp_dir"' EXIT

for src_dir in $src_dirs; do
    cp "$src_dir"/* "$tmp_dir"/
done
gzip -9 "$tmp_dir"/*

mkdir -p "$(dirname "$out_file")"
rm -f "$out_file"

# ext/freezefs has no __init__.py (freezefs 2.4 upstream ships it as an implicit namespace
# package) - PYTHONPATH=ext is what makes `python -m freezefs` resolve it, confirmed directly
# against the vendored copy (see ext/freezefs/__main__.py: `from freezefs.archive import main`).
PYTHONPATH="ext${PYTHONPATH:+:$PYTHONPATH}" python3 -m freezefs "$tmp_dir" "$out_file" \
    --on-import mount --target "$mount_target" --overwrite always --silent

echo "Wrote $out_file (mounts at $mount_target on import)"
